qq: 2265453790  # 运行时登录的 QQ 号
verifyKey: "INITKEYjOmhWeXk"  # MAH 的 verifyKey
recall: 60  # 涩图撤回等待时长（单位：秒）
# 如果你没有那么多涩图API可以填一样的URL
setu_api: "https://www.dmoe.cc/random.php"  # 涩图 API
setu_api2: "https://moe.jitsu.top/img/"  # 涩图 API 2
setu_api2_probability: 5 # 表示【涩图 API 2】的被调用的概率为 1/n